# If you don't have an API key yet, register your application at:
# 
# <YourShopURL>/admin/api (e.g. "http://shopname.myshopify.com/admin/api")
#
# Be sure to conceal these credentials if you make your application code public.
# If you're using Git, put the following line in a file called .gitignore in your
# repository root:
# 
#   config/shopify.yml
# 
# If you're using SVN, you can run this command from the application root:
# 
#   svn propedit svn:ignore ./config/shopify.yml
#
# You can also load your API credentials from the environment variables 
# SHOPIFY_API_KEY and SHOPIFY_API_SECRET.
#
# If you are deploying to Heroku, you use config vars (http://docs.heroku.com/config-vars) for this purpose:
#
#   heroku config:add SHOPIFY_API_KEY=b2da14e1291682a9dad049d4970f5541 SHOPIFY_API_SECRET=df6c9f0d84c9b7a65d92ec4132f7d877
development:
  api_key: b2da14e1291682a9dad049d4970f5541
  secret: df6c9f0d84c9b7a65d92ec4132f7d877

test:
  api_key: b2da14e1291682a9dad049d4970f5541
  secret: df6c9f0d84c9b7a65d92ec4132f7d877
    
production:
  api_key: b2da14e1291682a9dad049d4970f5541
  secret: df6c9f0d84c9b7a65d92ec4132f7d877
